name: Update badges

on:
  schedule: # execute every 12 hours
    - cron: "* */12 * * *"
jobs:
  update-readme:
    name: Update Readme with badges
    runs-on: ubuntu-latest
    steps:
      - name: Badges - Readme
        uses: pemtajo/badge-readme@main
